Class Examples for Project 1

In [1]:
import pandas as pd
import altair as alt

In [2]:
#url = "https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv"
names = pd.read_csv("names_year.csv")

How many babies are named ‘Oliver’ in the state of Utah for all years?

In [3]:
names.query('name == "Oliver"').UT.sum()

1704.0

What was the earliest year that the name ‘Felisha’ was used?

In [4]:
names.query("name == 'Felisha'")

,name,year,AK,AL,AR,AZ,CA,CO,CT,DC,...,TN,TX,UT,VA,VT,WA,WI,WV,WY,Total
135125,Felisha,1964,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
135126,Felisha,1965,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
135127,Felisha,1966,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0
135128,Felisha,1967,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
135129,Felisha,1968,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0
135130,Felisha,1969,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0
135131,Felisha,1970,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,...,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0
135132,Felisha,1971,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,48.0
135133,Felisha,1972,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,81.0
135134,Felisha,1973,0.0,6.0,8.0,0.0,5.0,0.0,0.0,0.0,...,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,76.0
135135,Felisha,1974,0.0,8.0,6.0,0.0,8.0,0.0,0.0,0.0,...,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90.0
135136,Felisha,1975,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,14.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,103.0
135137,Felisha,1976,0.0,6.0,8.0,0.0,7.0,0.0,0.0,0.0,...,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.0
135138,Felisha,1977,0.0,10.0,0.0,0.0,5.0,0.0,0.0,0.0,...,8.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,140.0
135139,Felisha,1978,0.0,6.0,6.0,0.0,6.0,0.0,0.0,0.0,...,9.0,14.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,105.0
135140,Felisha,1979,0.0,7.0,7.0,0.0,7.0,0.0,0.0,0.0,...,6.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,127.0
135141,Felisha,1980,0.0,7.0,6.0,0.0,9.0,0.0,0.0,0.0,...,5.0,11.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,95.0
135142,Felisha,1981,0.0,0.0,0.0,5.0,16.0,0.0,0.0,0.0,...,5.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90.0
135143,Felisha,1982,0.0,7.0,7.0,0.0,11.0,5.0,0.0,0.0,...,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,111.0
135144,Felisha,1983,0.0,0.0,0.0,5.0,13.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.0
135145,Felisha,1984,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,...,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0
135146,Felisha,1985,0.0,9.0,5.0,0.0,16.0,8.0,0.0,0.0,...,8.0,24.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,193.0
135147,Felisha,1986,0.0,0.0,6.0,0.0,32.0,6.0,0.0,0.0,...,7.0,33.0,0.0,0.0,0.0,6.0,0.0,7.0,0.0,204.0
135148,Felisha,1987,0.0,9.0,0.0,0.0,34.0,6.0,0.0,0.0,...,10.0,28.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,215.0
135149,Felisha,1988,0.0,6.0,6.0,10.0,29.0,5.0,0.0,0.0,...,10.0,27.0,5.0,6.0,0.0,5.0,0.0,5.0,0.0,244.0
135150,Felisha,1989,0.0,5.0,8.0,5.0,41.0,0.0,0.0,0.0,...,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,240.0
135151,Felisha,1990,0.0,7.0,8.0,0.0,38.0,5.0,0.0,0.0,...,9.0,25.0,6.0,6.0,0.0,6.0,0.0,0.0,0.0,223.0
135152,Felisha,1991,0.0,0.0,0.0,7.0,33.0,0.0,0.0,0.0,...,10.0,28.0,7.0,6.0,0.0,0.0,6.0,0.0,0.0,214.0
135153,Felisha,1992,0.0,0.0,0.0,5.0,26.0,0.0,0.0,0.0,...,13.0,26.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,181.0
135154,Felisha,1993,0.0,8.0,0.0,0.0,18.0,6.0,0.0,0.0,...,6.0,23.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,164.0
135155,Felisha,1994,0.0,5.0,0.0,5.0,21.0,0.0,0.0,0.0,...,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,119.0
135156,Felisha,1995,0.0,6.0,0.0,0.0,13.0,0.0,0.0,0.0,...,5.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,91.0
135157,Felisha,1996,0.0,0.0,6.0,0.0,14.0,0.0,0.0,0.0,...,0.0,20.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,76.0
135158,Felisha,1997,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,38.0
135159,Felisha,1998,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,...,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0
135160,Felisha,1999,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
135161,Felisha,2000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
135162,Felisha,2001,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,...,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0
135163,Felisha,2002,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
135164,Felisha,2003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
135165,Felisha,2004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
135166,Felisha,2005,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
135167,Felisha,2007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0

How many unique names does the names dataset contain?

In [5]:
len(names.name.unique())

7354

What is the range of years in the names dataset?

In [6]:
print(min(names.year))
print(max(names.year))

1910
2015

Project 1, Day 3 Class Examples

In [7]:
names[(names['name'] == "Gavin") | (names['name'] == 'Kyle')]
#or#
#names.query('name == "Gavin"')

names[names['name'].isin(['Gavin', 'Kyle'])]

,name,year,AK,AL,AR,AZ,CA,CO,CT,DC,...,TN,TX,UT,VA,VT,WA,WI,WV,WY,Total
143356,Gavin,1940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
143357,Gavin,1946,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
143358,Gavin,1947,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
143359,Gavin,1948,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
143360,Gavin,1952,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221976,Kyle,2011,12.0,47.0,24.0,59.0,217.0,49.0,39.0,0.0,...,40.0,118.5,45.0,94.0,0.0,74.0,39.0,16.0,0.0,2739.5
221977,Kyle,2012,9.0,31.0,30.0,42.0,203.0,42.0,47.0,6.0,...,51.0,206.0,40.0,86.0,6.0,61.0,55.0,16.0,0.0,2572.5
221978,Kyle,2013,9.0,27.0,28.0,45.0,178.5,31.0,37.0,9.0,...,43.0,112.0,33.0,61.0,6.0,38.0,33.0,18.0,0.0,2120.5
221979,Kyle,2014,5.0,24.0,24.0,38.0,299.0,27.0,28.0,6.0,...,33.0,98.5,29.0,64.0,0.0,51.0,35.0,10.0,0.0,2081.5
221980,Kyle,2015,10.0,26.0,16.0,40.0,283.0,29.0,28.0,0.0,...,39.0,127.0,33.0,59.0,0.0,40.0,29.0,15.0,9.0,2203.0

In [8]:
list_of_names = ['Gavin' , 'Nate' , 'Brigham']

compare_names = (names.query('name is in @list_of_names')
    .groupby('name')
    .mean()
    .filter(['AK', 'Total'])
    .sort_values('AK' , ascending = False))

compare_names

SyntaxError: Python keyword not valid identifier in numexpr query (<unknown>, line 1)